# Generated by Django 5.1.5 on 2025-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='filter',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('moderatsiyad', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor qilingan', 'Bekor qilingan')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
