# Generated by Django 5.1.5 on 2025-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sponser_filter_delete_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='filter',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('moderatsiyada', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor qilingan', 'Bekor qilingan')], max_length=200),
        ),
    ]
