# Generated by Django 5.1.5 on 2025-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sponser_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='spent_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
