# Generated by Django 5.1.5 on 2025-02-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sponser_spent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponser',
            name='spent_amount',
        ),
    ]
